<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Slim\\Views\\' => array($vendorDir . '/slim/views'),
    'Arcanedev\\QrCode\\' => array($vendorDir . '/arcanedev/qr-code/src'),
);
